name: CI

on:
	push:
		branches: [ main ]
	pull_request:
		branches: [ main ]

jobs:

	build:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2

			- name: Set up Go
			  uses: actions/setup-go@v2
			  with:
				  go-version: 1.17

			- name: Build
			  run: go build -v ./...

			- name: Test
			  run: go test -v ./...

	docker:
		needs: build
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2

			- name: Build the Docker image
			  run: docker build . --file Dockerfile --tag messenger-backend:$(date +%s)

			- name: Run Docker image
			  run: docker run messenger-backend:$(date +%s)